language: generic

sudo: required
services:
  - docker

before_install: 
  - docker build -t thomas/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true thomas/docker-react npm run test